# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 481383dea85533c32db7912e981035f588e2863b6101be67fd69aecc74445cb9ec73466c38294ac54ed1c903718be9377a03e2c99f0baea73e5e62e6df11930d

test:
  secret_key_base: 427b4fe44ef41ec220479ee09b5831b50c410ef97c69e2c464ab9e22fd279f16fa267ae6c9f67a926de14c4cd864021c2ae0e18618973e993e434e04a4f5f187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
